# Generated by Django 5.0.2 on 2024-04-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_categoria_cor_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="acessorio",
            name="categoria",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.categoria"),
        ),
        migrations.AddField(
            model_name="acessorio",
            name="cor",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.cor"),
        ),
        migrations.AddField(
            model_name="acessorio",
            name="marca",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="core.marca"),
        ),
        migrations.AddField(
            model_name="marca",
            name="nacionalidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
