# Generated by Django 5.0.2 on 2024-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_acessorio_categoria_acessorio_cor_acessorio_marca_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modelo", models.CharField(max_length=100)),
                ("acessorios", models.ManyToManyField(related_name="veiculos", to="core.acessorio")),
            ],
        ),
    ]
